---
- name: "Wordpress Installation"
  hosts: "ubuntu"
  become: true
  vars_files:
    - main.var
  tasks:
    - name: "Lamp - Installing Apache and mariadb server"
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      tags:
        - wordpress
        - drupal
    - name: "install pymsql"
      pip:
        name: pymysql
        state: present
      tags:
        - wordpress
        - drupal
    - name: "Lamp - Creating httpd.conf from template"
      template:
        src: port.conf.tmpl
        dest: /etc/apache2/ports.conf
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      tags:
        - wordpress
        - drupal
